### ISSUE TITLE
[doc] review all closed issues to consolidate Datwit info in admindoc

### ISSUE THREAD

**Issue by sorice** [datwit/landing3#163]
- During landing3 development many informations about Datwit were developed for the first time, like #108 #120 #101 #96...
- Review all closed issues in landing3 to formalize this information into Datwit LLC admindoc.
- Make small changes in admindoc and open ONE issue for Abel with the missing issues we need to review as founders.
- Take into account that this [issue](https://gitlab.sebastianaurei.com/datwit/mgmt/scrum-board/-/issues/34) in Datwit gitlab contains 108, 96 and 120.

**Comment by enmalidia** [comment]
Summarizing issues, a way to do it: 
https://allcode.com/how-to-export-github-issues-to-excel-easily/

**Comment by enmalidia** [comment]
[GitHubIssues_02072022.xlsx](https://github.com/datwit/landing3/files/9035294/GitHubIssues_02072022.xlsx)
[GitHubIssues-02072022.txt](https://github.com/datwit/landing3/files/9035295/GitHubIssues-02072022.txt)

**Comment by sorice** [comment]
The final resume with non duplicated details are in private gitlab management/development/2022_landing3_issues_summary
