### ISSUE TITLE
Los enlaces no aparecen con el color correcto

### ISSUE THREAD

**Issue by ybenitezf** [datwit/landing3#229]
Los enlaces en los post de los casos de estudio no se muestran correctamente 

![image](https://user-images.githubusercontent.com/8646381/201488317-007d8f58-a9a6-4d97-95ca-381d7e78766c.png)

**Comment by alcantara2575** [comment]
@sorice @ybenitezf mi propuesta es resaltar esos enlaces utilizando **el propio markdown**, ya se ha utilizado ese formato en otros textos. Si están de acuerdo me comentan para cerrar el issue

**Comment by sorice** [comment]
De acuerdo, cuando @ybenitezf me comentó no me acordé!
